---
- name: Copy the my.cnf
  copy:
    src: "resources/my.cnf"
    dest: "/etc/my.cnf"
  become: true
  delay: 5

- name: Restart mariadb
  service:
    name: mariadb
    state: restarted
  become: true
