---
- name: Shutdown all vms on hypervisors and reset performance vms
  hosts: performance-hypervisors
  roles:
    - hypervisor
  vars:
    ansible_user: root
  tasks:
    - name: sleep for ddns to kick in
      pause:
        minutes: 10
  tags:
    - setupvms

- name: Deploy candlepin and run performance test
  hosts: performance-candlepin-vm
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0/
  roles:
    - candlepin-user
  vars:
    ansible_user: jenkins
  tags:
    - runtest
