---
- name: Checkout branches from GitHub
  hosts: performance-candlepin-vm
  roles:
    - candlepin-checkout
  vars:
    ansible_user: jenkins
  tags:
    - checkout

- name: Shutdown all vms on hypervisors and reset performance vms
  hosts: performance-hypervisors
  roles:
    - hypervisor
  vars:
    ansible_user: root
    baseline_branch: "{{hostvars['performance-candlepin-vm']['baseline_branch']}}"
  tasks:
    - name: sleep for ddns to kick in
      pause:
        minutes: 2
  tags:
    - setupvms

- name: Setup mysql vm
  hosts: performance-mysql-vm
  roles:
    - mysql-user
  vars:
    ansible_user: root
  tags:
    - runtest

- name: Deploy candlepin and run performance test
  hosts: performance-candlepin-vm
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0/
  roles:
    - { role: candlepin-user, deploy_candlepin: true, provision_db: true, run_test: true }
  vars:
    ansible_user: jenkins
    baseline_branch: "{{hostvars['performance-candlepin-vm']['baseline_branch']}}"
  tags:
    - runtest
